## Data Structures

In [1]:
# Given the string 'Hello Python' give an index command that returns 'y'. Use the code below:
s = 'Hello Python'
# Code here
s[7]

'y'

In [2]:
# Reverse the string using indexing
s[::-1]

'nohtyP olleH'

In [3]:
# Give two methods of producing the letter 'l' using indexing.
# Method 1
s[2]

'l'

In [4]:
s[-9]

'l'

In [5]:
# Build this list [0,0,0] using two different methods
# Method 1
zero_list = [0] * 3
zero_list

[0, 0, 0]

In [6]:
# Method 2
[0 for i in range(3)]

[0, 0, 0]

In [7]:
range(3)

range(0, 3)

In [8]:
# Reassign 'Python' in this nested list to say 'Java' item in this list.
l = ['a', 'b',[3, 4,'Python']]
l[2][2] = 'Java'
l

['a', 'b', [3, 4, 'Java']]

In [9]:
# Using keys and indexing, grab the 'Python' from the following dictionary
d = {'First_key':[{'Nest_key':['Deep_key',['Python']]}]}
d['First_key'][0]['Nest_key'][1]

['Python']

Q: Can you sort a dictionary? Why or why not?

R: You can't sort a dictionary because it is not an iterable or sequence, it is mapping.

Q: What is the major difference between tuples and lists?

R: Tupples are inmutable, you can not change their elements. In a list you can change their elements.

In [10]:
# How do you create a tuple?
example_tuple = tuple([1, 2, 3])
example_tuple

(1, 2, 3)

In [11]:
# Final Question: What is the boolean output of the cell block below? 
# two nested lists
list_one = [5, 6,[7, 4]]
list_two = [1,2,{'key':4}]

#True or False?
list_one[2][0] >= list_two[2]['key']

True

## Python Statements 

In [13]:
# Use for, split(), and if to create a Statement that will print out words that start with 's'
st = 'Print only the words that start with s in this sentence'
for item in st.split():
    if item.startswith('s'):
        print (item)

start
s
sentence


In [14]:
# Use range() to print all the even numbers from 0 to 10.
for item in range(0, 10, 2):
    print (item)

0
2
4
6
8


In [15]:
# Use List comprehension to create a list of all numbers between 1 and 50 that are divisible by 3.
[ x for x in range(1, 50) if not x % 3 ]

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48]

In [16]:
[ x for x in range(1, 50) if x % 3 == 0 ]

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48]

In [19]:
# Go through the string below and if the length of a word is even print "even!"
st = 'Print every word in this sentence that has an even number of letters'
for word in st.split():
    if len(word) % 2 == 0:
        print (word + " is even!")
    else:
        print (word + " is odd")

Print is odd
every is odd
word is even!
in is even!
this is even!
sentence is even!
that is even!
has is odd
an is even!
even is even!
number is even!
of is even!
letters is odd


## Functions

Write a Python function to multiply all the numbers in a list.
* Sample List : [1, 2, 3, -4]
* Expected Output : -24

In [20]:
def multiply(numbers):  
    total = 1
    for x in numbers:
        total *= x  
    return total  

In [21]:
multiply([1,2,3,-4])

-24

Write a Python function that takes a list and returns a new list with unique elements of the first list.
* Sample List : [1,1,1,1,2,2,3,3,3,3,4,5]
* Unique List : [1, 2, 3, 4, 5]

In [22]:
def unique_list(l):
    x = []
    for a in l:
        if a not in x:
            x.append(a)
    return x

In [23]:
unique_list([1,1,1,1,2,2,3,3,3,3,4,5])

[1, 2, 3, 4, 5]

Write a Python function that accepts a string and calculate the number of upper case letters and lower case letters.
* Sample String : 'Hello Mr. Rogers, how are you this fine Tuesday?'
* Expected Output : 
  * No. of Upper case characters : 4
  * No. of Lower case Characters : 33

In [28]:
def up_low(s):
    d={"upper":0, "lower":0}
    for c in s:
        if c.isupper():
            d["upper"]+=1
        elif c.islower():
            d["lower"]+=1
        else:
            pass
    print ("Original String : ", s)
    print ("No. of Upper case characters : ", d["upper"])
    print ("No. of Lower case Characters : ", d["lower"])

In [29]:
s = 'Hello Mr. Rogers, how are you this fine Tuesday?'
up_low(s)

Original String :  Hello Mr. Rogers, how are you this fine Tuesday?
No. of Upper case characters :  4
No. of Lower case Characters :  33


## Numpy

1. Create a 3x3 identity matrix 
2. Create a 4x4x4 array with random values
3. Find A*B of the two matrices
4. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [33]:
# 1
import numpy as np
I = np.identity(4)
I , I.shape

(array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]), (4, 4))

In [34]:
# 2
R = np.random.rand(4,4,4,4)
R , R.shape

(array([[[[0.80067244, 0.58476959, 0.77677603, 0.19876249],
          [0.69936189, 0.89764855, 0.37236043, 0.68047971],
          [0.18248872, 0.87864937, 0.22292693, 0.78252406],
          [0.574382  , 0.36558986, 0.3660828 , 0.11823408]],
 
         [[0.09422998, 0.71512538, 0.7215991 , 0.4253975 ],
          [0.8995352 , 0.31481302, 0.19931883, 0.10040408],
          [0.61330405, 0.36187456, 0.53699153, 0.48749507],
          [0.2987458 , 0.27916601, 0.81751909, 0.95465793]],
 
         [[0.1390904 , 0.28049617, 0.96128242, 0.57034295],
          [0.46779208, 0.97762336, 0.52965271, 0.02341401],
          [0.49126253, 0.99950586, 0.50502685, 0.29896068],
          [0.72805964, 0.18027039, 0.72448102, 0.5193453 ]],
 
         [[0.24096347, 0.77219222, 0.72107429, 0.22365599],
          [0.52640562, 0.60210746, 0.35412455, 0.29641705],
          [0.9699442 , 0.10880035, 0.07022871, 0.68097466],
          [0.68264331, 0.72413545, 0.29448797, 0.02413981]]],
 
 
        [[[0.10627083, 0.

In [ ]:
prod = np.dot(I, R)

In [38]:
# 
F = np.array([4.5, 5.4, 6.4])
F

array([4.5, 5.4, 6.4])

In [39]:
A = np.arange(15).reshape(5, 3)
A = A * 1.2 
A

array([[ 0. ,  1.2,  2.4],
       [ 3.6,  4.8,  6. ],
       [ 7.2,  8.4,  9.6],
       [10.8, 12. , 13.2],
       [14.4, 15.6, 16.8]])

In [40]:
B = np.arange(6).reshape(3, 2)
B = B * 2.8
B

array([[ 0. ,  2.8],
       [ 5.6,  8.4],
       [11.2, 14. ]])

In [41]:
prod_A_B = np.dot(A, B)

In [42]:
prod_A_B

array([[ 33.6 ,  43.68],
       [ 94.08, 134.4 ],
       [154.56, 225.12],
       [215.04, 315.84],
       [275.52, 406.56]])

In [43]:
# import numpy
import numpy as np
# Import pandas
import pandas as pd
import matplotlib.pyplot as plt
# Make figures appear in-line within the notebook
%matplotlib inline

In [44]:
df_survey = pd.read_csv("surveys.csv")

In [45]:
plot_names = df_survey["plot_id"]

In [46]:
plot_names.unique()

array([ 2,  3,  7,  1,  6,  5,  8,  4, 11, 14, 15, 13,  9, 10, 17, 16, 20,
       23, 18, 21, 22, 19, 12, 24])

In [47]:
plot_specie = df_survey["species_id"]

In [48]:
plot_specie.unique()

array(['NL', 'DM', 'PF', 'PE', 'DS', 'PP', 'SH', 'OT', 'DO', 'OX', 'SS',
       'OL', 'RM', nan, 'SA', 'PM', 'AH', 'DX', 'AB', 'CB', 'CM', 'CQ',
       'RF', 'PC', 'PG', 'PH', 'PU', 'CV', 'UR', 'UP', 'ZL', 'UL', 'CS',
       'SC', 'BA', 'SF', 'RO', 'AS', 'SO', 'PI', 'ST', 'CU', 'SU', 'RX',
       'PB', 'PL', 'PX', 'CT', 'US'], dtype=object)